version: '3.8'

services:
  invoiceshelf-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: invoiceshelf-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      APP_ENV: production
      APP_KEY: ${APP_KEY}
      APP_URL: ${APP_URL}
      DB_CONNECTION: mysql
      DB_HOST: invoiceshelf-db
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MAIL_MAILER: smtp
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
    networks:
      - internal
      - coolify
    depends_on:
      - invoiceshelf-db

  invoiceshelf-db:
    image: mariadb:10.5
    container_name: invoiceshelf-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - internal

  invoiceshelf-nginx:
    image: nginx:alpine
    container_name: invoiceshelf-nginx
    restart: unless-stopped
    depends_on:
      - invoiceshelf-app
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - internal
      - coolify

volumes:
  dbdata:


networks:
  internal:
  coolify:
    external: true
