version: '3.8'

services:
  invoiceshelf-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: invoiceshelf
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html:delegated
    environment:
      APP_ENV: production
      APP_KEY: ${APP_KEY}
      APP_URL: ${APP_URL}
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MAIL_MAILER: ${MAIL_MAILER}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_FROM_ADDRESS: ${MAIL_FROM_ADDRESS}
      MAIL_FROM_NAME: ${MAIL_FROM_NAME}
    networks:
      - internal
    healthcheck:
      test: [ "CMD", "php-fpm", "-t" ]
      interval: 10s
      timeout: 5s
      retries: 3

  invoiceshelf-nginx:
    image: nginx:alpine
    container_name: nginx-alpine
    restart: unless-stopped
    volumes:
      - .:/var/www/html:delegated
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - internal
    depends_on:
      invoiceshelf-app:
        condition: service_healthy

volumes:
  dbdata:


networks:
  internal:
    external: true
